[build]
  command = "yarn install && yarn build"
  publish = "dist"

[[headers]]
  for = "/_expo/static/js/web/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"
    "Cache-Control" = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
